/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(udp_source_vb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(57ba835c1ccadff78219dbcc8774be96)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aistx/udp_source_vb.h>
// pydoc.h is automatically generated in the build directory
#include <udp_source_vb_pydoc.h>

void bind_udp_source_vb(py::module& m)
{

    using udp_source_vb    = gr::aistx::udp_source_vb;


    py::class_<udp_source_vb, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<udp_source_vb>>(m, "udp_source_vb", D(udp_source_vb))

        .def(py::init(&udp_source_vb::make),
           D(udp_source_vb,make)
        )
        



        ;




}








